name: Pull Requests
on: pull_request_target
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:3.2
        ports:
          - 27017:27017
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
        with:
            ref: ${{ github.event.pull_request.head.sha }}
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Run tests
        run: ./sbt test
      - uses: kentaro-m/auto-assign-action@v1.1.2
        with:
          configuration-path: ".github/auto_assign.yml"
